panel: fix i2c related compilation errors
Currently building the project results in the following messages:

  undefined reference to `i2c_smbus_read_byte_data'
  undefined reference to `i2c_smbus_write_byte_data'

The happens because i2c related code and header files were reorganized
upstream. As a result we now need a different i2c include file and a
specially linked library to compile the project.

Make the necessary adjustments.

Signed-off-by: Nikita Kiryanov <nikita@compulab.co.il>